### ISSUE TITLE
Binary release available?

### ISSUE THREAD

**Issue by ericscharff** [Turbo240Z/dr_c64#1]
I attempted to build this, but unfortunately I do not have XCode, nor do I have any of the third party dependencies needed to assemble and link the program.

I'd love to see Dr Mario on a C-64!

Could you provide a link to the d64 for direct download, or perhaps update the README to where to obtain the dependencies for building a binary?

**Comment by tonyfruzza** [comment]
@ericscharff There was a preview of this released many years ago using the original graphics before redoing those.

http://csdb.dk/release/?id=119362

I've purposefully left parts out as this was to be a commercial release game initially. When work and home life permits I'll release a more complete version.

The current development version not only has new graphics, but also new sound track, story line, more animations, high score, and a couple game modes. Thanks for the interest.

Here's a video showing some of the changes:
https://www.youtube.com/watch?v=Ude5X7qpYv0

**Comment by ericscharff** [comment]
Thanks for the update. Looking forward to a release!
